version: "3.8"

services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    restart: unless-stopped
    ports:
      - "127.0.0.1:8090:8080"
    environment:
      DATABASE_URL: "postgres://jarvis:jarvis_pass@172.18.0.4/miniflux?sslmode=disable"
      RUN_MIGRATIONS: "1"
      CREATE_ADMIN: "1"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "miniflux2026!"
      BASE_URL: "https://rss.myserver-ai.ru"
    networks:
      - root_default

networks:
  root_default:
    external: true
