server:
  address: tcp://0.0.0.0:9091
  tls:
    certificate: /config/tls.crt
    key: /config/tls.key

log:
  level: debug

identity_validation:
  reset_password:
    jwt_secret: 13622181ae11cf6cf3f5e2a325ae024d540bdc0ccf2364984d1ec81cc7887108

authentication_backend:
  file:
    path: /config/users_database.yml

session:
  secret: e4627b90c1a9f5986a8ed0ffa4501ced74657a47b10ac4d3349170471a8c6f54
  expiration: 12h
  inactivity: 2h
  cookies:
    - domain: myserver-ai.ru
      authelia_url: https://auth.myserver-ai.ru
      default_redirection_url: https://home.myserver-ai.ru

storage:
  local:
    path: /config/db.sqlite3
  encryption_key: 52d88a025ee33c459ac098e57abe62697582dbcc3cadba11b28e60bdd6559fc6

notifier:
  filesystem:
    filename: /config/notification.txt

access_control:
  default_policy: deny
  rules:
    - domain: "auth.myserver-ai.ru"
      policy: bypass
    - domain: "nextcloud.myserver-ai.ru"
      policy: bypass
    - domain: "vault.myserver-ai.ru"
      policy: bypass
    - domain: "myserver-ai.ru"
      resources:
        - "^/webhook/.*$"
      policy: bypass
    - domain: "home.myserver-ai.ru"
      policy: two_factor
    - domain: "photos.myserver-ai.ru"
      policy: two_factor
    - domain: "myserver-ai.ru"
      policy: two_factor
    - domain: "music.myserver-ai.ru"
      policy: two_factor
