services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    network_mode: host
    volumes:
      - /opt/authelia/config:/config
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
