server {
    listen 80;
    server_name music.myserver-ai.ru;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name music.myserver-ai.ru;

    ssl_certificate /.acme.sh/music.myserver-ai.ru_ecc/fullchain.cer;
    ssl_certificate_key /.acme.sh/music.myserver-ai.ru_ecc/music.myserver-ai.ru.key;

    client_max_body_size 10M;

    location / {
        proxy_pass http://10.8.0.27:4533;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }
}
