conn IKEv2-EAP-MSCHAPv2
  keyexchange=ikev2
  auto=add
  rekey=no
  dpdaction=clear
  dpddelay=300s
  fragmentation=yes
  forceencaps=yes
  left=%defaultroute
  leftid=147.45.238.120
  leftauth=pubkey
  leftcert=server-cert.pem
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  right=%any
  rightauth=eap-mschapv2
  rightsourceip=10.0.2.0/24
  rightdns=8.8.8.8,8.8.4.4
  rightsendcert=never
  eap_identity=%identity
  ike=aes256-sha256-modp3072,aes256-sha256-modp2048,aes128-sha256-modp3072,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048
  esp=aes256-sha256,aes128-sha256,aes256-sha1,aes128-sha1
