version: "3"
services:
  strongswan:
    image: philplckthun/strongswan
    container_name: strongswan
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - VPN_IPSEC_PSK=MyServerVpnKey2026
      - VPN_USER=sergei
      - VPN_PASSWORD=Vpn2026Spb!
