
conn ikev2-psk
  left=%defaultroute
  leftid=147.45.238.120
  leftauth=psk
  leftsubnet=0.0.0.0/0
  right=%any
  rightauth=psk
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="8.8.8.8 8.8.4.4"
  dpddelay=30
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes256-sha2;modp2048,aes128-sha2;modp2048,aes256-sha1;modp2048,aes128-sha1;modp2048
  phase2alg=aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
